### PR TITLE
Fix/replication

### LINKED ISSUE #46: [Bug] Replication does not filter by key expression
### Describe the bug

Reported on our discord server: https://discord.com/channels/914168414178779197/1224725858984530053

When multiple storages use a same bucket, but are associated with different and non overlapping key expressions, the replication mechanism replicates entries that are not associated with the key expression of the storage.

The solution to this would be to filter the entries based on the key expression.

### To reproduce

N/A

### System info

N/A

### PR DESCRIPTION
**Pull request by DariusIMP**
This PR edits the `get_all_entries` function from the S3 backend in order to filter entries based on the key expression associated to the storage, avoiding that entries that are associated to keys that do not intersect the storage key to be replicated.

Closes #46

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -281,30 +281,52 @@ impl Storage for S3Storage {
...
+                }
+            };
+
+            if object_key == NONE_KEY {
+                return None;
+            }
+
+            let key = path_prefix
+                .as_ref()
+                .map_or(object_key.to_string(), |prefix| {
```
Comment (chachi) [inline src/lib.rs:300]: question: Is `object_key.to_string()` is redundant as `object_key` is already a string? Could it just be moved into the `.map_or` to avoid a new clone and allocation?

Comment (chachi) [inline src/lib.rs:300]: suggestion: perhaps this could use fewer clones if the whole block was turned into 
```
path_prefix.as_ref().unwrap_or_default() + object_key
```
as that would avoid cloning `object_key` potentially twice?

File: src/lib.rs [hunk 2]
```diff
@@ -281,30 +281,52 @@ impl Storage for S3Storage {
             .map_err(|e| zerror!("Get operation failed: {e}"))?
             .map_err(|e| zerror!("Get operation failed: {e}"))?;
 
-        let futures = objects.into_iter().map(|object| {
+        let path_prefix = self.config.path_prefix.to_owned();
```
Comment (chachi) [inline src/lib.rs:284]: question: Does `config.path_prefix` need to be an owned string or could it be a `&str` here?

Comment (DariusIMP) [reply src/lib.rs]: We can't as it is right now, maybe we could refactor the S3Key struct to contain a &Option<String> for the prefix, but I wouldn't do it for the time being.

**Comment by DariusIMP** [comment]
Ok did some modifications after testing it with an internally developed shell script, that basically declares two storages pointing to a same bucket but with different key expressions. The test works fine when doing wildcard queries. Therefore the #46 issue regarding this problem within the replication context should be solved.

File: src/lib.rs (hunk 2 above)
Comment (J-Loudet) [reply src/lib.rs]: This seems like a reasonable change with a limited scope. I don't think the lifetime will contaminate much.
Is there something I am missing?

File: src/config.rs [hunk 3]
```diff
@@ -147,6 +152,10 @@ impl S3Config {
         }?)
     }
 
+    fn load_key_expr(config: &StorageConfig) -> ZResult<OwnedKeyExpr> {
+        Ok(config.key_expr.to_owned())
+    }
+
```
[the remark this answers is not in the document]
Comment (DariusIMP) [reply src/config.rs:158]: For the sake of readability I had thought, since we have multiple other 'load' functions called upon construction of the S3Config struct. But yes, maybe that's not enough justification for this one line function.

File: src/lib.rs (hunk 2 above)
Comment (DariusIMP) [reply src/lib.rs]: Ok I addressed the comment. As a thought, there are other elements in this codebase that can be converted into references, it'll be worth a small refactor in the future.

File: src/utils.rs [hunk 4]
```diff
@@ -12,30 +12,22 @@
...
-    pub value: Value,
-    pub metadata: Option<HashMap<String, String>>,
-}
-
-pub struct S3Key {
-    pub prefix: Option<String>,
+pub struct S3Key<'a> {
+    pub prefix: &'a Option<String>,
     pub key: String,
 }
```
Comment (J-Loudet) [inline src/utils.rs:23]: Please change to this instead:
```suggestion
pub struct S3Key<'a> {
    pub prefix: Option<&'a str>,
    pub key: OwnedKeyExpr,
}
```
- This video covers in details why `Option<&T>`: https://www.youtube.com/watch?v=6c7pZYP_iIE
- An `OwnedKeyExpr` contains an `Arc<str>`, less expensive to clone than a `String`

File: src/config.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (J-Loudet) [reply src/config.rs:158]: Please remove it.

**Review by J-Loudet — CHANGES_REQUESTED** [review]

**Review by J-Loudet — APPROVED** [review]
👍 

I believe there is room for improvement, in particular the `aws-sdk-s3` dependency needs to be updated, the version used (0.21.0) is far behind the latest one (1.23.0).

**Comment by DariusIMP** [comment]
> 👍
> 
> I believe there is room for improvement, in particular the `aws-sdk-s3` dependency needs to be updated, the version used (0.21.0) is far behind the latest one (1.23.0).

That's true. I opened issue #55 to tackle it shortly.
